// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUkhNyYC1IF-6LOHKQHZgcj3SGGXwvYWI',
    appId: '1:890167664943:web:2ede230e70eb04cd1e01da',
    messagingSenderId: '890167664943',
    projectId: 'authflow-o64yi',
    authDomain: 'authflow-o64yi.firebaseapp.com',
    storageBucket: 'authflow-o64yi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCniHNMTBwHIGte6ybDd1v0iqwjqlVqrG8',
    appId: '1:890167664943:android:eeec7f3a795f32ec1e01da',
    messagingSenderId: '890167664943',
    projectId: 'authflow-o64yi',
    storageBucket: 'authflow-o64yi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_H8wmqQmdk13fLvUSaYAz1r739y8KrE',
    appId: '1:890167664943:ios:f821cc4d2f6fc2bb1e01da',
    messagingSenderId: '890167664943',
    projectId: 'authflow-o64yi',
    storageBucket: 'authflow-o64yi.firebasestorage.app',
    iosBundleId: 'com.example.loginPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx_H8wmqQmdk13fLvUSaYAz1r739y8KrE',
    appId: '1:890167664943:ios:f821cc4d2f6fc2bb1e01da',
    messagingSenderId: '890167664943',
    projectId: 'authflow-o64yi',
    storageBucket: 'authflow-o64yi.firebasestorage.app',
    iosBundleId: 'com.example.loginPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUkhNyYC1IF-6LOHKQHZgcj3SGGXwvYWI',
    appId: '1:890167664943:web:d461445c098c8cf81e01da',
    messagingSenderId: '890167664943',
    projectId: 'authflow-o64yi',
    authDomain: 'authflow-o64yi.firebaseapp.com',
    storageBucket: 'authflow-o64yi.firebasestorage.app',
  );
}
